### ISSUE TITLE
Custom time periods

### ISSUE THREAD

**Issue by liamcain** [liamcain/obsidian-periodic-notes#98]
# Goal

Allow for creating custom periodicity for tracking things such as:
- Sprints (often 2-3 intervals)
- Semesters (Non-deterministic cycling, has fixed start and end date)

## Implementation Plan

- UI in the settings to name the granularity
- Notes of that granularity will require specifying the following frontmatter:

```
semester:
  count: 2 # some way to enumerate which semester you're on

  # optional, allows for better integration with the date switcher
  start_date: {{date:YYYY-MM-DD}}
  end_date: {{date:YYYY-MM-DD}} 
```

### Restrictions

- Each periodicity will need some type of enumeration. To keep this simple, I think starting at count 1 and incrementing each time should solve most use cases.
